### PR TITLE
Prevent double-click recorder bug

### LINKED ISSUE #3411: A double-click on the record icon can disable recording
Quickly click on a record button twice and you may get a console error
```
RecorderIcon.tsx:54 Tried to record for an entry before finishing a recording on another entry.
```
This prevents any further audio recording and is not cleared up by refreshing the page. You have to log out and back in to clear the issue.

### PR DESCRIPTION
**Pull request by imnasnainaec**
Fixes #3411 and prevents trying to upload an empty audio file.

Stress-test with rapid repeated clicks on the same record button. Then pause a do a normal recording on the same button.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/3414)

### CODE REVIEW

File: src/components/Pronunciations/AudioRecorder.tsx [hunk 1]
```diff
@@ -34,6 +45,8 @@ export default function AudioRecorder(props: RecorderProps): ReactElement {
     // Prevent starting a recording before a previous one is finished.
     await stopRecording();
 
+    setClicked(true);
```
Comment (hahn-kev) [inline src/components/Pronunciations/AudioRecorder.tsx:48]: Since this is after an await it's possible that the user clicks it in-between no?

Comment (imnasnainaec) [reply src/components/Pronunciations/AudioRecorder.tsx]: Good point.

**Review by jasonleenaylor — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> Dismissed @hahn-kev from a discussion.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/3414)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @hahn-kev)
