### PR TITLE
[MergeDups] Implement SignalRHub for duplicate finder

### LINKED ISSUE #3720: MergeDuplicate errors (524) if duplicate-finding takes longer than 100 seconds
**Describe the bug**

The duplicate finder is quick when finding sets of words with identical vernacular form. It takes a lot longer when those are exhausted, because next are sets of similar-vernacular-form words, which need to have their similarities ordered. This can take several minutes on a multi-thousand word project. If it takes over 100 seconds, we get a 524 error, which is Cloudflare's custom timeout error. We need to do one of the following:

- Rewrite the merge tool
  - Signal when duplicates are found (as we do with the export)?
  - Poll until it's done?
- ~Update our Cloudflare settings with this particular function to not timeout (for 10 minutes?)~ [only available for Enterprise plans]

### PR DESCRIPTION
**Pull request by imnasnainaec**
Resolves #3720

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/3725)

### CODE REVIEW

**Review by jasonleenaylor — COMMENTED** [review]
I think you should investigate memory cache as an alternative to the ConcurrentDictionary.
https://learn.microsoft.com/en-us/dotnet/api/system.runtime.caching.memorycache?view=netframework-4.8

> Reviewed 3 of 23 files at r1, 7 of 12 files at r4.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/3725#-:-OOTuuSm0xxCEU4Zwgq6:b-nv8o7)* status: 9 of 27 files reviewed, all discussions resolved (waiting on @imnasnainaec)

File: Backend/Controllers/MergeController.cs [hunk 1]
```diff
@@ -118,7 +123,41 @@ public async Task<IActionResult> GetPotentialDuplicates(
...
+            // See: https://stackoverflow.com/a/64614779/1398841
+            _ = Task.Run(() => GetDuplicatesThenSignal(projectId, maxInList, maxLists, userId));
+
+            return Ok();
+        }
+
+        internal async Task<bool> GetDuplicatesThenSignal(string projectId, int maxInList, int maxLists, string userId)
+        {
+            // Use counter to ensure that only the most recent duplicate request succeeds per user.
+            var counter = Interlocked.Increment(ref _mergeCounter);
```
Comment (hahn-kev) [inline Backend/Controllers/MergeController.cs:140]: it's not clear to me, is there an assumption that `_mergeCounter` is persisted between requests? I would verify this as I believe by default controllers are request scoped and not singletons meaning each request `_mergeCounter` would start at 0.

Comment (imnasnainaec) [reply Backend/Controllers/MergeController.cs]: Done

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/3725)* status: 8 of 27 files reviewed, 1 unresolved discussion (waiting on @hahn-kev and @jasonleenaylor)

**Review by imnasnainaec — COMMENTED** [review]
> Dismissed @hahn-kev from a discussion.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/TheCombine/3725)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @hahn-kev)
